### ISSUE TITLE
Unreadable selected text

### ISSUE THREAD

**Issue by wp-xyz** [michalgw/mphexeditor#3]
Normally the HexEditor draws the selection as yellow text on black background. Under some circumstances, when the HexEditor is not focused, the text color turns to black (or another very dark color), too, and thus is not readable any more.

Unfortunately I could not figure out the exact conditions for this issue to appear. But you can reproduce it in your demo (HexEditor/project2):

- Delete the ini file of the project to avoid the effect of already-changed colors.
- Compile and run the demo
- Load some file, select a range of bytes: The selected text is yellow on black
- Click "Edit" > "Go to...". While the dialog box is on the screen the selected text is black (or maybe navy) on black and not readable.

**Comment by michalgw** [comment]
Fixed in rev. 5733c4b.
The problem was in FadeToGray function. Only occurred when "GraySelectionIfNotFocused" property is True (as in the example).
Thanks!
