### ISSUE TITLE
hexeditor bug : function UNDO dont work on 64 bits 

### ISSUE THREAD

**Issue by docroger** [michalgw/mphexeditor#4]
Hello,
Sorry for my bad english, i am french.

Hexeditor is a well component.

I have a problem with UNDO function : work well if compiled in 32 bits on lazarus 2.0.12 (window 10 Pro x64) but compiled in 64 bits dont work (delete last char and finally data position or size error message).  

Is it possible to fix this behavior ?

Thanx for your good work,
Roger//

**Comment by michalgw** [comment]
Hello,
I just posted changes to repository. Please try latest version. Hope the problem is resolved. Please check and reopen issue if it still doesn't work.

**Comment by docroger** [comment]
Sorry, dont work on x64 windows.
Look the problem with the example compiled with Lazarus.

![hexaedit](https://user-images.githubusercontent.com/33279081/121938387-0df06900-cd4c-11eb-967f-b0023f6484ee.gif)

**Comment by michalgw** [comment]
It looks like it was before the changes but now I can't get this bug. 
How do you install this package? Are you using files from GitHub or Online Package Manager? These changes aren't in OPM yet, so try files from the GitHub repository. If you are using sources from the GitHub repository, try to remove "lib" subdirectory from "src" directory and form sample project directory, then recompile the package and project.

**Comment by docroger** [comment]
my bad.
Sorry.

I dont use the correct file.

Good job. You catch the problem.

Thank you.
