### ISSUE TITLE
Caret not shown on Lazarus/Linux

### ISSUE THREAD

**Issue by Colpocorto** [michalgw/mphexeditor#5]
When the component is used on Linux, the caret is not shown (on both the nibble or the character data entry).

Steps to reproduce it:

-Install Lazarus 2.2.0 on Linux (used latest version of Linux Lite, a derivative of Ubuntu).
-Open the Sample2 included project.
-Build and run the application.
-On the Sample2 application, open any file.
-Try to modified on the hex editor.

The caret is not shown (either the full or underline one, so no matter if overwrite or insert modes are selected).
All the available LCLWidgetTypes have been tried, with no success.

**Comment by Colpocorto** [comment]
Update: it seems that the caret is visible if the app is built with QT.

But it still fails with the rest of the widget sets.  Is this any well-known limitation?

**Comment by michalgw** [comment]
I can confirm that the problem exists. I think I found a problem - I just updated the code. Can you check if it works now?

**Comment by Colpocorto** [comment]
Hi,

I have updated the code with the committed file but the issue still persists on Gtk2 AND now it also happens with QT5 (that was working fine before the change).

**Comment by michalgw** [comment]
Caret handling is tricky in non win-LCL... I just updated the code. Please test.

**Comment by Colpocorto** [comment]
Tested. Back to the initial status: QT5 works. GTK2 does not.

**Comment by michalgw** [comment]
Sorry... pushed more changes. You can check?

**Comment by Colpocorto** [comment]
YES!!

It worked perfectly on both GTK2 and QT5 now !!!!  Awesome!
You did a great job.

It now works even on Linux with a simple X-Window server and an Openbox windows manager without the need for any external dependencies. 

Thank you for your work!
![image](https://user-images.githubusercontent.com/24856281/186515558-3f4f32b6-3a72-4a7e-bb9e-ee41f0d03775.png)
