### ISSUE TITLE
Height and Width

### ISSUE THREAD

**Issue by ProgrammingHobby** [michalgw/mphexeditor#7]
Is it possible to get the height and width of the HexEditor in pixels?
So that, for example, a panel or the client size of a frame can be better adapted.

**Comment by michalgw** [comment]
I'm not sure what you mean by that. Are you referring to width and height of data displayed, as in the attached image?
If so, there is currently no way to retrieve these values. But I can add appropriate methods to get these values.
![hexedit_wh](https://github.com/michalgw/mphexeditor/assets/8337677/6c36bb96-b38a-4d31-8a1a-b924c4b34a10)

**Comment by ProgrammingHobby** [comment]
Yes exactly, I mean the area of the displayed data as you have marked it in the screenshot. If it is possible, it would be nice to have methods with which these values can be obtained.

**Comment by michalgw** [comment]
I added two methods: DisplayWidth and DisplayHeight. Keep in mind that they do not take into account size of control's borders. If this solution is sufficient for you then close this issue.

**Comment by ProgrammingHobby** [comment]
I have compiled my test application with the latest changes. Now I can query the current display area and set up the frame accordingly.
Many thanks for the great HexEditor component.
