### ISSUE TITLE
Caret Position

### ISSUE THREAD

**Issue by ProgrammingHobby** [michalgw/mphexeditor#8]
When navigating with the cursor keys, press twice to move down. On the first press the caret disappears and then appears as expected one line further down on the second press.

**Comment by michalgw** [comment]
If you installed component from Online Package Manager then there is an older version there that has a caret problem. Try to install current version from this github repository.
However, if you are using current version from github then specify what operating system and widgetset you are using.

**Comment by ProgrammingHobby** [comment]
I have the MPHexEditor from your Github repository. Under Windows the cursor control works, under Linux it comes to the described problems. I use KUbuntu 22.04 64bit LTS as Linux on my development system. The widget set is GTK2.

**Comment by michalgw** [comment]
I just updated code. Please test and if it works ok then please close the issue.

**Comment by ProgrammingHobby** [comment]
I have compiled my test application with the latest changes. Now the cursor control works perfectly.
Many thanks for the great HexEditor component.
